### PR TITLE
[FEATURE] Add partition

### PR DESCRIPTION
**Pull request by Chalarangelo**
## Description
**Lodash** #100 -> https://lodash.com/docs/4.17.4#partition

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Chalarangelo** [comment]
@atomiks I thought about it when I was writing the snippet, it looks slightly confusing like that, I feel. Plus we have a few snippets with the same kind of style, so I decided to go with that style for consistency.

**Comment by atomiks** [comment]
@Chalarangelo see the edit- you can also stick the ternary inside the `acc[]`, which makes it shorter

**Comment by Chalarangelo** [comment]
`Array.concat()` is terriby slow, so we avoid using it for such cases in general. Sticking the ternary inside the `[]` is not a bad idea, however the comma operator next to that will just be a bit too much and the rest of the snippets don't use it anyways, so I guess just the ternary should be enough of an improvement.

**Comment by skatcat31** [comment]
Reduce is a weird monster, but this works as advertised. To only awkward part is needing the parens, which harms readability but not enough to not consider it

**Pull request merged**
