### PR TITLE
[FEATURE] renameKeys

### PR DESCRIPTION
**Pull request by yazeedb**
## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by yazeedb** [comment]
@Chalarangelo You're welcome, thanks for this amazing repo!

I took a page from [Ramda](http://ramdajs.com/)'s book and supplied the data last, to support currying. If one wishes to change the same keys on many objects, the param order allows partial application.

```js
const renameFirstAndLastName = renameKeys({ fname: 'firstName', lname: 'lastName' });

renameFirstAndLastName(obj1);
renameFirstAndLastName(obj2);
renameFirstAndLastName(obj3);
...
```

**Comment by Chalarangelo** [comment]
@yazeedb Thanks for clarifying! I never thought of that in that way to be honest. It makes quite a lot of sense then. I'll keep this open for another 12 hours or so, see if any of the other maintainers have anything they might want to add to the discussion. If nobody disagrees, I'll merge this in the morning! 😉

**Comment by yazeedb** [comment]
@Chalarangelo Sounds excellent, have a good night! 😁

**Comment by skatcat31** [comment]
We do the Data first, Transformer last because this is meant to be a learning library, allowing us to have a footprint of smallest to largest part.

For Ramda Like partial applications we have `flip` in the adapters and curry as well, allowing us to easily adapt to that model as well. IT was the entire reason behind the Adapters section.

I myself love Ramda(you can actually see me lurking in their gitter constantly, just like with Node and Express), but we decided against that model specifically because of the adapter category and wanting to make sure the snippets were more readable

**Comment by skatcat31** [comment]
For more information feel free to check out adapters and the specific ones being `call`, `flip`, and `curry`

**Comment by skatcat31** [comment]
@Chalarangelo we've had that conversation before there buddy. It's why all of our snippets are now callbacks last( refer to the simple http debacle )

**Comment by skatcat31** [comment]
Now back to the EXACT footprint of these types of functions where it is `(applicable, data)` our current precedence is library first IIRC based on a word snippet... Let me go dig that up

**Comment by skatcat31** [comment]
I'll be opening an issue about order of declaration of operations and maps... It looks like we've gotten a little inconsistent again. Until then I think this is perfectly fine the way it is.

**Pull request merged**
