### PR TITLE
[ENHANCEMENT] Handle CRLF for splitting lines on Windows

### PR DESCRIPTION
**Pull request by sudo-suhas**
## Description

This updates the pattern for splitting lines so that it is Windows compatible. See https://stackoverflow.com/questions/21895233/how-in-node-to-split-string-by-newline-n.

## What does your PR belong to?
- [ ] Website
- [X] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have checked that the changes are working properly
- [X] I have checked that there isn't any PR doing the same
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by sudo-suhas** [comment]
I get what you mean. But as it turns out, if you split with `\n`, the `\r` gets left behind(if there was one). This caused issues for me in regex matching:

```
λ node
> let readFileLines = filename => fs.readFileSync(filename).toString('UTF8').split('\n');
> let lines = readFileLines('./example-input.txt')
> console.log(lines[0])
Writing Fast Tests Against Enterprise Rails 60min
> const re = /^\D+(\d+min)$/i
> re.test(lines[0])
false
> readFileLines = filename => fs.readFileSync(filename).toString('UTF8').split(/\r?\n/);
[Function: readFileLines]
> lines = readFileLines('./example-input.txt')
[ 'Writing Fast Tests Against Enterprise Rails 60min',
  'Overdoing it in Python 45min',
  '' ]
> re.test(lines[0])
true
```

**Comment by Chalarangelo** [comment]
I think it would be nice to match the regex and use `replace('\n')` to actually normalize the file first, then `split(/\n/)`, which should work properly then.

**Comment by sudo-suhas** [comment]
Splitting on `/\r?\n/` is the same thing in a single step, no? Or is it code clarity that you are aiming to improve?

**Comment by Chalarangelo** [comment]
Ah, I thought what you described was happening after you updated the snippet. My bad, I get it now! 👍

**Pull request merged**
