### PR TITLE
[ENHANCEMENT] smooth scrolling on iOS devices

### PR DESCRIPTION
**Pull request by rainshen49**
## What does your PR belong to?
- [x] Website
- [ ] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Chalarangelo** [comment]
As MDN says:
> **Non-standard**
> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

So I'm against adding this, unless it solves some real big issue on the website.

**Comment by atomiks** [comment]
@Chalarangelo that message is meaningless, it's an important/widely-used property to fix overflow scrolling on iOS

**Comment by Chalarangelo** [comment]
[caniuse](https://caniuse.com/#search=-webkit-overflow-scrolling) does not even recognize it, is it really that big of a deal? (Never been on an iOS device, I don't even understand what we are talking about here)

My assumption was that if MDN says it's technically invalid, there's no reason to have it, right?

**Comment by atomiks** [comment]
On iOS, when scrolling scrollable divs (not the body however) without it, the scrolling has no inertia which makes scrolling feel really sluggish. It's non-standard but only applies to iOS and shouldn't be going away soon, so it's fine to use.

**Comment by Chalarangelo** [comment]
Ok, reopening and merging. Whatever quirky thing that is, no problem adding one line of CSS I guess if it doesn't affect anything else.

**Comment by fejes713** [comment]
@Chalarangelo iOS handles native scrolling a bit differently so this should solve that problem.

**Pull request merged**
