### PR TITLE
[FEATURE] hz

### PR DESCRIPTION
**Pull request by atomiks**
## Description

Returns the number of times a function executed per second after `iterations` times. 

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by atomiks** [comment]
Interesting application:

```js
const isAnimationFriendly = (fn, millisecondBudget = 10) => 
  hz(fn) > 1000 / millisecondBudget
```

"Animation friendly" means the function can execute within `10ms` (`millisecondBudget`), which is the budget for creating performant animations (16.666ms for 60 fps, but with browser overhead it's said to be 10ms).

**Comment by skatcat31** [comment]
For Chrome vs Node speed: One of them has a DOM engine, the other does not. AFAIK that is what causes such a large difference in speed between the two. When the DOM engine is told to be turned off, Chrome can often be seen being just as fast as NodeJS( PhantomJS uses a rendering engine and a headful Chrome, Headless Chrome does not use a rendering engine ): https://hackernoon.com/benchmark-headless-chrome-vs-phantomjs-e7f44c6956c

**Comment by Chalarangelo** [comment]
@skatcat31 has a good point. That's what I was thinking as well. `performance.now()` is pretty accurate and it actually depends on the environment, so it should give a decently accurate measurement about performance in said environment. Therefore, I think we are good to go with this.

**Comment by Chalarangelo** [comment]
By the way, lucky snippet: As soon as we merged it, it's featured on the landing page. 😆

**Pull request merged**
