### PR TITLE
[FEATURE][ADD] Add forOwn and forOwnRight

### PR DESCRIPTION
**Pull request by Chalarangelo**
## Description

Two methods for objects from lodash.

**Lodash[ADD]** #100 -> https://lodash.com/docs/4.17.4#forOwn
**Lodash[ADD]** #100 -> https://lodash.com/docs/4.17.4#forOwnRight

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## [Lodash Backlog](https://github.com/Chalarangelo/30-seconds-of-code/issues/100)

- [x] I added the prefix [UPDATE: `method.md`] or [ADD: `method.md`]
- [x] I have referenced the `method` to the lodash backlog.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by skatcat31** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries if only this were ES6...

**Comment by skatcat31** [comment]
Should we call this `forOwn` or should we make it an object copier that is more akin to a `mapObj`? Or should we do a `mapObj` function alongside/at all?

**Comment by Chalarangelo** [comment]
I'm thinking a `mapObj` function could be worthwhile as a matter of fact. While we're at it, maybe we should ditch the `forIn` and `forInRight` ones, as they are too much trouble and I do not see any reason to really add those very specific functions to begin with.

**Comment by skatcat31** [comment]
Although to be fair
```js
const mapObj = (obj, fn) => forOwn(JSON.parse(JSON.stringify(obj)), fn)
```

**Pull request merged**
