### PR TITLE
snippet to implement toString

### PR DESCRIPTION
**Pull request by arjunmahishi**
## Description

Added new snippet

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by arjunmahishi** [comment]
Not sure if this is a legit PR because `toString()` is natively available. But it covers two exceptional cases (-0 and null) as seen [here](https://lodash.com/docs/4.17.4#toString)

**Comment by arjunmahishi** [comment]
@skatcat31 I don't get it. How is this related to `toString()` ?

**Comment by skatcat31** [comment]
```js
toString(0) // '-0'
toString(false) // '-0'
```

**Comment by arjunmahishi** [comment]
Ohh right!! didn't realize that! it's midnight here :P

**Comment by arjunmahishi** [comment]
How do I fix this?

**Comment by skatcat31** [comment]
think of the edge cases surrounding -0 specifically in terms of math.

```js
if ( x === 0 && something specific to -0 ) '-0'
```

**Comment by iamsoorena** [comment]
I have an opinion, :D I'm not a fan of this approach. since we can almost do this with every other native method and what's the outcome?

**Comment by Chalarangelo** [comment]
@iamsoorena I agree, extending native methods should only be done when they handle common edge-cases or it helps somewhere (i.e. a really long method name or a property that is hard to remeber and used a lot or a lesser known property or method that we want to expose new developers to). My vote, too, is to not merge this snippet and mark it as natively implemented in #100.

**Comment by arjunmahishi** [comment]
cool..

**Comment by skatcat31** [comment]
@arjunmahishi What I was trying to guide you to was.

```js
1/0 == Infinity
1/null == Infinity
1/-0 == -Infinity
```

**Comment by arjunmahishi** [comment]
@skatcat31 I will reopen the PR in the morning. Thanks :smile:

**Comment by skatcat31** [comment]
@arjunmahishi I wouldn't reopen the PR as it was decided it might not be the right place here since toString is native and the use cases for this are fairly limited(I've never ONCE ran into a -0), but we still appreciate the PR even if it did get turned down.

**Comment by Chalarangelo** [comment]
@arjunmahishi since this only deals with very specific corner cases and we're kind of not very much in love with the idea so far, better focus your energy on some other snippet, no need to waste your time on this one. Plus, if we decide this should be added, you've already implemented like 80% of it.

**Pull request closed without merging**
