### PR TITLE
Create convert-json-date.md

### PR DESCRIPTION
**Pull request by sekmenhuseyin**
I hope you like this

### CODE REVIEW

**Comment by Chalarangelo** [comment]
I'll need a bit to test this, but it looks promising. Thanks for contributing!

**Comment by Emgo-Dev** [comment]
The getMonth() method returns current month as index of 11, so u need to +1 to it in your return right? Or am I missing something? Is it also common to store dates like this in JSON?

**Comment by Chalarangelo** [comment]
As far as my experience suggests, I don't think anyone stores months zero-indexed. Any opinions?

**Comment by Emgo-Dev** [comment]
This function seems more useful for its' parsing of a JSON string. In practice should be passed to a formatter function.

**Comment by Emgo-Dev** [comment]
@Chalarangelo  I just did a test in the browser...is that no reliable?

**Comment by Chalarangelo** [comment]
I don't suppose this will work any differently on Node @Emgo-Dev, so it probably stores months starting with January at zero.

**Pull request merged**
