### PR TITLE
[ENHANCEMENT] Simplified isArrayLike

### PR DESCRIPTION
**Pull request by Bruce-Feldman**
## Description

Simplied isArrayLike to directly check if the given input is iterable rather than indirectly by checking if the spread operator throws an exception.

This code is shamelessly stolen from https://stackoverflow.com/questions/18884249/checking-whether-something-is-iterable

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Bruce-Feldman** [comment]
Oh whoops... I forgot to push up the documentation update.  Sorry about that.

**Comment by Bruce-Feldman** [comment]
Note that this code is taken from https://stackoverflow.com/questions/18884249/checking-whether-something-is-iterable

**Comment by Bruce-Feldman** [comment]
The Codacy review seems to be waffling back and forth on whether strings should be single or double quoted?  I could have sworn that Codacy finally said the code was up to standards then then said that double quotes are a problem?

**Comment by Chalarangelo** [comment]
Our code style enforces single quotes. Codacy is fiddly at best, has caused a lot of head scratching before.

**Comment by Bruce-Feldman** [comment]
Thanks for letting me know.  What would you like me to change to get this through review?

**Comment by Chalarangelo** [comment]
@Bruce-Feldman I can take care of it before I merge it, not a huge issue.

**Comment by Bruce-Feldman** [comment]
Wonderful, thanks.

**Pull request merged**
