### PR TITLE
[FIX] toSnakeCase

### PR DESCRIPTION
**Pull request by kriadmin**
## Description
Fixed a typology error in toSnakeCase examples 

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by kriadmin** [comment]
@iamsoorena I updated the second to last example and deleted the last example because that example didn't look good to me. If you think I am wrong I can add it again.

**Comment by iamsoorena** [comment]
@kriadmin from my point of view you didn't change it. and yes please add last example back. it shows extreme situation.

**Comment by kriadmin** [comment]
Ok I will add the last example back.
And see carefully I changed `// toKebabCase("AllThe-small Things") -> "all_the_smal_things"` to `// toSnakeCase("AllThe-small Things") -> "all_the_smal_things"` See the `Kebab` is replaced by `Snake`
`

**Comment by kriadmin** [comment]
@iamsoorena After reading your comments many times I finally understood what you meant.
By typo I actually meant `toKebabCase` to `toSnakeCase` but you meant to change `smal` to `small`.
Now I changed both and thanks

**Pull request merged**
