### PR TITLE
Create Speech_synthesis.md

### PR DESCRIPTION
**Pull request by meetzaveri**
Hey, I think this is the coolest one I found! Hope this snippet gets attraction

### CODE REVIEW

**Comment by elderhsouza** [comment]
@meetzaveri This looks awesome! Nice one!

**Comment by Chalarangelo** [comment]
@meetzaveri I love this! I will review soon and test! Great job, thanks for sharing this!

**Comment by meetzaveri** [comment]
Glad ! Thanks @elderhsouza and @Chalarangelo

**Comment by elderhsouza** [comment]
@meetzaveri As of right now, it doesn't comply with the styleguide, maybe refactor it to not use var and to use arrow functions.

**Comment by meetzaveri** [comment]
@elderhsouza  Yes I did update it with es6 approach!

**Comment by fejes713** [comment]
`const speak = message => {
 +  const msg = new SpeechSynthesisUtterance(message)
 +  const voices = window.speechSynthesis.getVoices()
 +  msg.voice = voices[0]
 +  window.speechSynthesis.speak(msg)
 + }`

**Comment by elderhsouza** [comment]
Maybe online the voice assignment:

```js
const speak = message => {
  const msg = new SpeechSynthesisUtterance(message);
  msg.voice = window.speechSynthesis.getVoices()[0];
  window.speechSynthesis.speak(msg);
}
```

**Comment by meetzaveri** [comment]
Done @elderhsouza

**Pull request merged**
