### PR TITLE
add pick code snippet

### PR DESCRIPTION
**Pull request by kingdavidmartins**
similar to lodash pick method 

https://lodash.com/docs/4.17.4#pick

### CODE REVIEW

**Comment by darrenscerri** [comment]
This is a very useful method. However, this is a simpler solution:

```js
const pick = (obj, arr) => arr.reduce((acc, curr) => (acc[curr] = obj[curr], acc), {});
```

**Comment by kingdavidmartins** [comment]
Nice!! I definitely agree the solution is much more elegant is simpler.

@darrenscerri  I was thinking what if the arr passed with keys the users wants doesn't exist.  Rather than just reducing over something that doesn't exist and returning undefined. I can use filter to filter it out.

**Comment by darrenscerri** [comment]
Good point. Something like this guards that:

```js
const pick = (obj, arr) => arr.reduce((acc, curr) => (curr in obj && (acc[curr] = obj[curr]), acc), {});
```

**Comment by kingdavidmartins** [comment]
Nice! Agreed 💯

**Pull request merged**
