### PR TITLE
Create standard-deviation.md

### PR DESCRIPTION
**Pull request by atomiks**
http://www.calculator.net/standard-deviation-calculator.html

As a one-liner it's really long, feel free to optimize the formatting here (or shorten it further somehow).

### CODE REVIEW

**Comment by Chalarangelo** [comment]
I like this. I'll see if i can figure out a way to shorten it a bit, but it doesn't look bad as-is. Thanks for the contribution!

**Comment by atomiks** [comment]
Noticed there was an extra parameter for no reason... removed it!

**Comment by atomiks** [comment]
Hmm, since there are two types of standard deviation (`population` and `sample`), maybe there can be a flag as a second parameter, like so?

```js
const standardDeviation = (arr, useSample) =>
  Math.sqrt(
    arr.reduce((acc, val) => acc.concat(Math.pow(val - arr.reduce((acc, val) => acc + val, 0) / arr.length, 2)), [])
       .reduce((acc, val) => acc + val, 0) 
    / (arr.length - useSample ? 1 : 0)
  );
```

**Comment by Chalarangelo** [comment]
I'd like that, maybe we can set the `useSample` to default to one of the two? (your choice which one)

**Comment by atomiks** [comment]
I'm not sure which one is more common/useful 🤔 , not a statistician hah! Maybe I'll look to see.

**Comment by atomiks** [comment]
http://smallbusiness.chron.com/difference-between-sample-population-standard-deviation-22639.html

https://stats.stackexchange.com/questions/269/what-is-the-difference-between-a-population-and-a-sample

It looks like they both have their use cases, but I think `sample` might be more common?

>The population is the set of entities under study. For example, the mean height of men. This is a hypothetical population because it includes all men that have lived, are alive and will live in the future. I like this example because it drives home the point that we, as analysts, choose the population that we wish to study. Typically it is impossible to survey/measure the entire population because not all members are observable 

>**Instead, we could take a subset of this population called a sample and use this sample to draw inferences about the population under study, given some conditions. Thus we could measure the mean height of men in a sample of the population which we call a statistic and use this to draw inferences about the parameter of interest in the population.** It is an inference because there will be some uncertainty and inaccuracy involved in drawing conclusions about the population based upon a sample. This should be obvious - we have fewer members in our sample than our population therefore we have lost some information.

The `N - 1` is meant to be a corrective measure for samples, which are probably more common, so you can switch it to `usePopulation ? 0 : 1` instead. No need for a default value.

**Comment by atomiks** [comment]
Had to de-one-linerify it because the mean was constantly being recalculated, which is bad for perf obviously 😄 . Updated it to cache it in the const

**Comment by Chalarangelo** [comment]
Hey @atomiks, sorry this has taken so long. Add a default parameter to the second argument and we're good to go. I'll see if we can shorten the description a little bit, as this feels a bit too long to me.

**Comment by atomiks** [comment]
> Add a default parameter to the second argument and we're good to go

It's falsy by default though, so there's no need to?

**Comment by Chalarangelo** [comment]
Better be explicit about it @atomiks. 😉

**Pull request merged**
