### PR TITLE
[ENHANCEMENT] a better difference

### PR DESCRIPTION
**Pull request by lvzhenbang**
## Description

a faster and more concise of difference

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Chalarangelo** [comment]
I'm pretty certain that in a previous discussion we had decided that `Set` was the best and most intuitive way to go about this, due to the fact that it is pure ES6 and showcases a neat native feature. I'm voting to keep the snippet as-is.

**Comment by Pl4gue** [comment]
Oh alright :+1: :smile: ,didn't know about this discussion @Chalarangelo Well, we can keep it as it is now as well.

**Comment by Chalarangelo** [comment]
I also think that we run a jsPerf and `Set` was faster, but I cannot verify this at this time. Can anyone check and give us some solid evidence on that?

**Comment by skatcat31** [comment]
`Set` is faster according to design(constant time lookup as an object map with key === value(not really, but conceptually), whereas includes will always be O(x*n) where `x == traversed objects`.

JSPerf confirms this with `Set` being faster in all cases including ordered array case

**Pull request closed without merging**
