### PR TITLE
Create onUserInputChange.md

### PR DESCRIPTION
**Pull request by atomiks**
## Description

Runs the supplied callback whenever the user changes their input method (mouse or touch).
It's the most robust solution I had come up with for my tooltip library.

Simply using a userAgent or `'ontouchstart' in window` fail in a lot of cases. 

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by fejes713** [comment]
Great snippet 👍 , however:
>CONTRIBUTING.md
> Snippets should be short (usually below 10 lines)

Considering this, this won't be a great great idea to merge. Maybe, we could make separate `.md` where we would keep those longer useful snippets.

**Comment by atomiks** [comment]
I've used the comma operator to make it shorter. Still over 10 lines tho..

**Comment by fejes713** [comment]
@Chalarangelo any opinion about this one? After the changes it's much shorter, I think we could let this one merge into our codebase

**Comment by skatcat31** [comment]
While more than ten lines, it shows some useful management for detecting touches versus clicks. The question is how is that useful?

I think it's helpful if you want to hide certain things based on touch versus type... but I don't know when I'd ever do that. Maybe for disabling tooltips or changing how tool tips work, but often if that's the case I use a tip box and an onfocus handler for the form to update the tip box with a bound message on the element...

I think it's cool, but I'm struggling to find where I'd want to use it and when it'd be a good design decision to do so

@atomiks where would you use this snippet?

**Comment by atomiks** [comment]
@skatcat31 in my tooltip library, there is a `hideOnClick` option by default. This only applies to mouse devices, since it won't ever show the tooltip on touch if they're using that input method.  There's a couple other options too that need to distinguish between the two, but it's relatively rare I guess. Still I think it shows a technique for detecting it

**Comment by skatcat31** [comment]
If you're displaying tooltips on click instead of onFocus I think you're using the tooltips the wrong way. Touch users should also be able to see the tooltip for the form input, and what happens with tab navigation with your tooltip library?

**Comment by atomiks** [comment]
It shows them on `mouseenter focus` (allowing tabbed nav), but clicking the element will hide the tooltip. For touch devices this doesn't apply -- it's just a tap to show it, then a tap elsewhere to hide it.

**Comment by skatcat31** [comment]
... I think no matter what we can all agree that stylized tooltips SUCK... I use the title field since it displays on interaction and hover, and fades out on input( the default browser tooltip ) and if I need a stylized one, I use a tip box that floats and follows with an explanation along with the form, and will get updated by the onfocus event of the inputs will fire an event to update the tips box with a string
```js
const updateTip = (function(node, text){ node.innerHTML = text }).bind(null, document.getElementById('tipBox'))
```
```html
<input type='text' onfocus='updateTip(`Hi mom!`)'>
```
since now whoever does the page can update the tipbox however they want, but there are infinitely many ways to do it... that I find it hard to find cases for this code to justify it without it being extremely specific. Maybe we should do an advanced snippet category on a seperate page with much longer explinations and examples? Maybe each advanced is a different page?

**Comment by Chalarangelo** [comment]
@skatcat31 We might eventually add a category for more advanced snippets, but I think we can all agree this is an interesting one to have, even if slightly longer than the average snippet in the repo. I am merging this just because it's really cool and because I think we can get away with a few snippets being a bit more advanced or longer for the sake of showcasing something that many devs might not be familiar with.

@atomiks I shortened the description a tiny bit, just to make sure people don't get intimidated by its length. I also removed some curly brackets from an `if` statement, as they were not necessary.

**Pull request merged**
