### PR TITLE
ADD: negate.md

### PR DESCRIPTION
**Pull request by michael-gutman**
## Description
Add negate.md snippet
**Part of** #100  

**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#negate 

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## [Lodash Backlog](https://github.com/Chalarangelo/30-seconds-of-code/issues/100)

- [x] I added the prefix [UPDATE: `method.md`] or [ADD: `method.md`]
- [x] I have referenced the `method` to the lodash backlog.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by skatcat31** [comment]
Great first contribution! It's a helper function extremely useful in composition, but I'm not certain what category it belongs in or if it's one that require demystifying. Now if we want to start a logic category I'm all for it!

Other helpful Functions in the logic category include `if`, `ifElse`, `and`, `or`, etc. but at that point we'd be recreating Ramda, and you might as well use Ramda if you're going to go that heavily into FP composition...

**Comment by skatcat31** [comment]
Also please remove resolves #100 from your description or it will close that issue. It should be referenced, but not resolved

**Comment by Chalarangelo** [comment]
@kingdavidmartins In general, the `tagger` (un)categorizes new snippets and we can tag them retroactively on our own. So, based on the fact that this snippet works and nobody thinks that we shouldn't add it, I will merge and tag myself after the next automatic build.

@skatcat31 I agree we should add some logic functions to showcase a few examples, even if we do not implement the whole of Ramda. After all, people can learn from them. I will tag this as `logic` and I hope someone will PR `if`, `ifElse`, `and`, `or` etc. It's a great place to start and should help demistify a popular library's implementation.

**Comment by michael-gutman** [comment]
Hello! Thanks for accepting my PR! I wanted to confirm if I should run tagger or not for any future contributions, and also I noticed that the merged file has !**fun**(...args) instead of !**func**(...args), does this need another PR?

**Comment by Chalarangelo** [comment]
Yep, I probably messed this up when updating, PR it asap please!

**Pull request merged**
