### PR TITLE
[ENHANCEMENT] Simplified nth Element

### PR DESCRIPTION
**Pull request by Bruce-Feldman**
## Description

Simplified the implementation of nth Element to avoid unnecessary branching.
Updated documentation to reflect reality - the function would return undefined (not []) if the index was not in range.  This is maintained in the current implementation.

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Chalarangelo** [comment]
This changes behavior in the snippet itself, as the edge-case returns `undefined` instead of `[]` now. To be honest, this is not an unwelcome change as it feels more consistent with the codebase and it was never well documented and tested properly to begin with. I will run some tests, see if everything works as expected and probably merge this afterwards.

**Comment by Bruce-Feldman** [comment]
I can't seem to reproduce nthElement's returning [] on out of bounds values (https://repl.it/repls/ProductiveAwesomeLocation).  Could you describe the inputs that cause this behaviour so I can try to keep the functionality consistent?

**Comment by Chalarangelo** [comment]
It's quite possible the snippet's description was wrong in this case. I can't seem to reproduce it either.

**Comment by Bruce-Feldman** [comment]
Thanks for confirming.

**Comment by skatcat31** [comment]
Wasn't the `n, n+1` case for performance concerns with large arrays? If that's the case wouldn't it be better to update the description to note that and introduce that idea that large arrays are sometimes problems?

**Comment by Chalarangelo** [comment]
@skatcat31 We might need to run some perfs on arrays with a half a million objects. I think it's not that much a performance issue, but rather a memory issue. Might be worth checking out and finding what kind of limitations there are.

**Comment by skatcat31** [comment]
... come to think of it isn't this just a really badly performing example of infinitely many other ways to implement this?

```js
array.find((val, ind) => ind == n)
array[n]
etc()
```

**Comment by Bruce-Feldman** [comment]
This all makes sense.  Should we optimize for the case where n is negative as well?

**Comment by skatcat31** [comment]
> Should we optimize for the case where n is negative as well?

That's a great reason to keep `.slice`!

**Comment by Bruce-Feldman** [comment]
I've been thinking about how to implement the negative case with minimal memory cost, it seems as though:
```
[1, 2].slice(-1, 0) // []
[1, 2].slice(-2, -1) // [1]
```
This means that a working version should probably look something like:
```
const nthElement = (arr, n = 0) => (n === -1 ? arr.slice(n) : arr.slice(n, n + 1))[0];
```
This has the additional benefit that it will now reject out of range negative values as well.

**Comment by skatcat31** [comment]
That version has other issues as well sadly(out of bounds breaking, more memory usage on positive index, etc.)

probably more like:

```js
const nthElement = (arr, n = 0) => (n == 0 ? arr.slice(n) : arr.slice(n, n + 1))[0];
```

**Comment by Bruce-Feldman** [comment]
@skatcat31 
The version you propose doesn't work with n = -1:
```
const nthElement = (arr, n = 0) => (n == 0 ? arr.slice(n) : arr.slice(n, n + 1))[0];
nthElement([1], -1) // undefined
```
Did you mean n < 0 instead of n == 0?  Then we are right back where we started, which is fine with me.  I guess the question would be if we cared about optimizing memory consumption of the current implementation for large negative values.

That said, I don't understand your objections with the following:
```
const nthElement = (arr, n = 0) => (n === -1 ? arr.slice(n) : arr.slice(n, n + 1))[0];
```
It should not use extra memory on positive indexes.  I did note that it breaks backwards compatibility - large negative indices now return undefined.  I am not sure if this is a feature or a bug (I am leaning towards a feature).

**Comment by skatcat31** [comment]
ah never mind I misread the snippet. You're right I shouldn't have any objections.

**Comment by Bruce-Feldman** [comment]
Is there something I can do to help this PR get through?

**Comment by skatcat31** [comment]
Nope you've done your part. I try not to merge things unless they fix something because I want @Chalarangelo and the others to get the credit. I do more of the 'what are we missing or what concerns do we have here' stuff. Sometimes if they're busy I'll merge if it's been a week since last change. However this one looks good and has had enough deliberation

**Comment by Chalarangelo** [comment]
Ah, it's August and I'm sort of lazy lately. I try to merge PRs daily but then I get distracted a lot. Thanks @skatcat31 for merging this one! 👍

**Comment by Bruce-Feldman** [comment]
Thanks for getting to this!

**Pull request merged**
