### PR TITLE
[Feature] Add flip adapter

### PR DESCRIPTION
**Pull request by skatcat31**
Added flip adapter and adapter category to tags database

I have run into a problem that when I run the builder it does not build the category

### CODE REVIEW

**Comment by skatcat31** [comment]
Forgot the PR template. It isn't there in gitkraken

**Comment by Chalarangelo** [comment]
To the next reviewer (if they merge): tag as `adapter` in the database.

**Comment by Chalarangelo** [comment]
Alright, 2 reviews approving and changes made to fix issues, are we ready to merge then?

**Comment by iamsoorena** [comment]
@skatcat31 thank you. you are doing great.

**Pull request merged**
