### PR TITLE
Create recordAnimationFrames.md

### PR DESCRIPTION
**Pull request by atomiks**
## Description

An interesting / esoteric snippet I came up with to debug a problem with someone's library (smooth scroller when clicking an anchor tag)

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Chalarangelo** [comment]
I like the idea, but the snippet is probably far too specific, so I cannot see too many valid use-cases. I'm voting to move this to the archive. Also, there are a ton of missing semicolons in the snippet and the length is a tiny bit on the long side (which is not a real issue, provided how short each line is, but it might look intimidating). I'd like to hear more feedback from the team on this.

**Comment by atomiks** [comment]
I use semi-colonless style, but it will get fixed by linter/prettier anyway so I didn't bother

**Comment by Chalarangelo** [comment]
Ok, so the only issue remaining is the usability and if it should be added to the main listing or the archive as a result? @atomiks can you think of any common use-cases where one might want this? I suspect I am not really giving the snippet as much credit as I should.

**Comment by atomiks** [comment]
Well for the problem I had, something was occuring on every animation frame (the scroll position was changing), so I wanted to "record" each frame to see what the value of `window.scrollY` was to debug it.

I guess its main use is anything to do with animation. You might want to grab the value of something (such as styles of an element, etc) while it's animating, which this easily allows you to do.

**Pull request merged**
