### PR TITLE
Create factors.md

### PR DESCRIPTION
**Pull request by kriadmin**
## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by kriadmin** [comment]
@Chalarangelo I am not sure I shorten it further and even If I am able to remember what `pretteir` did to `palindrome` 😆

**Comment by Chalarangelo** [comment]
Good point, I'll see if I can shorten it by making some changes, but don't expect too much yet.

**Comment by Chalarangelo** [comment]
@kriadmin I'd rather we converted this to `primeFactors` instead, so that we can shorten the code and make sure this works for just the most common use-case. As it currently stands, it is pretty slow and very hard to understand in 30 seconds or less.

**Comment by kriadmin** [comment]
@Chalarangelo primeFactors is not good as it combine all the common use cases (I myself have felt the need for it two times this week while solving codewars). I think we should keep all of the existing functionality.

**Comment by Chalarangelo** [comment]
Well maybe remove the `powers` part as it adds a lot of overhead to the method? Snippets should do one thing and one thing only, this does 3 right now (which could be two or three snippets in their own right).

**Comment by kriadmin** [comment]
@Chalarangelo Ok we can remove the powers and prime part if you allow me to make seperate snippets for them 😄 Please 🙏

**Comment by Chalarangelo** [comment]
Just the powers part is not necessary, the rest can stay as it is pretty simple and usable! 😉 

Already updated, but adding the comment for clarity in case someone else stumbles upon this discussion!

**Pull request merged**
