### PR TITLE
fix broken test in tomorrow.test.js

### PR DESCRIPTION
**Pull request by kingdavidmartins**
## Description

fixes failing the `npm test` command

## What does your PR belong to?
- [ ] Website
- [ ] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [x] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Chalarangelo** [comment]
This *fix* actually breaks the test as it tests today's date against tomorrow's date. The test I had worked just fine before, when I tested it locally.

**Comment by kingdavidmartins** [comment]
huh. That's very interesting. Going to post the result I get. Just fetched & pulled the updated master `branch` 

Yet when I run `npm test` I get the following

**Comment by Chalarangelo** [comment]
@kingdavidmartins no idea why, but it worked on the Travis build and my local installation, maybe your node installation is outdated? It also works properly on my browser (I mean building the date like that).

**Comment by kingdavidmartins** [comment]
Going to log the result & post it. 

alt

**Comment by kingdavidmartins** [comment]
Currently running `node v9.4.0`

**Comment by kingdavidmartins** [comment]
Reproduced the same results 

repl link -> https://repl.it/repls/RotatingTightBluefish

alt

**Comment by kingdavidmartins** [comment]
it appears to happen when being parsed by `new Date()` checked MDN and fixed it. It was the format of the returned string of our `tomorrow.md`

**Comment by kingdavidmartins** [comment]
Results 

repl link -> https://repl.it/repls/ChartreuseUnwrittenPerch

alt

**Comment by kingdavidmartins** [comment]
Results 

repl link -> https://repl.it/repls/ChartreuseUnwrittenPerch

alt

**Comment by kingdavidmartins** [comment]
@Chalarangelo  going to fix and submit a PR

**Pull request merged**
