### PR TITLE
[FEATURE] Add chunksArray.md

### PR DESCRIPTION
**Pull request by kriadmin**
## Description
It might look like like `chunk` snippet but it is different. I couldn't write a great description sorry 😞 . Please someone look at the examples and improve the description.
## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by kriadmin** [comment]
@skatcat31 `sunset size`?

**Comment by skatcat31** [comment]
Sorry phone has auto correct. Sub set

**Comment by kriadmin** [comment]
@skatcat31 I still don't understand what you mean by `sub set size mismatch`? If you mean that the `num` is greater than `arr.length` than I already have example for that. Can you please add example yourself. I will be busy today So I won't be able to edit it. 😞

**Comment by kriadmin** [comment]
@kingdavidmartins It is the intended behaviour.  Can you make an description from the examples? I can't come up with a great description

Also about the commits some old commits from old are coming too and I don't know why 😕 .Also some old files were remaining like the RPN ones so there are commits to remove them.

**Comment by Chalarangelo** [comment]
This snippet is not usable in any use-cases `chunk` isn't and the results are quite confusing, as the first one returns an array with 6 elements, while the original has 5 elements. Due to this behavior and the snippet being virtually identical to an existing snippet otherwise, I am closing the PR.

**Comment by kriadmin** [comment]
@Chalarangelo It might not have many use cases but I have needed this snippet once and many people might need it. If not in the main snippets folder it deserves to be in the archive atleast.

**Comment by skatcat31** [comment]
not reopening, however clarifying what I meant by chunk sub set size mismatch:
image
The description makes it confusing which behavior should happen in such cases

**Pull request closed without merging**
