### PR TITLE
Simplify hide

### PR DESCRIPTION
**Pull request by Siarhei-Zharnasek**
Simplify hide [ENHANCEMENT]

No need to use destructuring because of modification of each element in the input array

## What does your PR belong to?
- [ ] Website
- [X] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have checked that the changes are working properly
- [X] I have checked that there isn't any PR doing the same
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Siarhei-Zharnasek** [comment]
@Chalarangelo but now NodeList has forEach in all major versions of browsers

**Comment by flxwu** [comment]
yep, @Siarhei-Zharnasek is right there, NodeList should be supported by all browsers already except maybe for some ancient ones.

https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach

**Comment by Chalarangelo** [comment]
Didn't know about that. Thanks @flxwu for checking this and merging!

**Comment by Siarhei-Zharnasek** [comment]
@flxwu thank you for clarification :)

**Pull request merged**
