### PR TITLE
Update symmetricDifference

### PR DESCRIPTION
**Pull request by EthanOrange**
No const
One time new Set()
One line code style

## Description

**Resolves** #(issue number) 

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by skatcat31** [comment]
I'm not sure this was ever working as intended in either version...

From Wikipedia:

```
For example, the symmetric difference of the sets {1,2,3} and {3,4} is {1,2,4}.
```

We may want to check that the symmetric difference is correct since we should not get ANY repeats as a repeat would mean it's in both sets wouldn't it? I'm going to do some more review. We may have a bug in this snippet

**Comment by Chalarangelo** [comment]
A repeat means it's twice in one of the arrays, @skatcat31.

**Comment by skatcat31** [comment]
If that's what we want then we should make new snippet for unique symmetrical differences

**Comment by Chalarangelo** [comment]
@skatcat31 That sounds like a bit of a convoluted name but it's what I was thinking of, too. Tests should also be more refined and better defined to make sure these edge cases are documented properly.

**Comment by skatcat31** [comment]
Then we'll want some changes on this one so that it doesn't unique

**Comment by Chalarangelo** [comment]
I'll follow up on this PR tomorrow, probably keep the original snippet as-is and use the PR's code to create a new snippet for `uniqueSymmetricalDifference`. I'll also add tests and examples to showcase the difference between the two.

**Comment by EthanOrange** [comment]
I really want to complete this code snippet.
but my English is very bad. I can't express the difference between `symmetricDifference` and `uniqueSymmetricalDifference`. 😔

**Comment by skatcat31** [comment]
`uniqueSymmetricalDifference` can be fixed to `uniqueSymmetricDifference` so that they are parodied names.

**Pull request merged**
