### PR TITLE
refactor(anagrams): improve code legibility

### PR DESCRIPTION
**Pull request by jobsamuel**
IMHO _anagrams_ snippet is AWESOME but it's kinda hard to understand for those who are new in Javascript. So, I just renamed some parameters in order simplify its complexity, and of course improve its legibility :raised_hands:

### CODE REVIEW

**Comment by jobsamuel** [comment]
Great :tada: 

I'm agreed with you, it's ok to keep `index` as `i` because is pretty common :+1:

**Comment by Chalarangelo** [comment]
I also shortened `value` to `val`, descriptive enough. I think this is a lot better now. Thanks a lot for the help!

**Comment by Chalarangelo** [comment]
@Villanuevand, I am retroactively improving snippets as much as possible. If you see something that is hard to read, please submit PRs. 😉

**Comment by Villanuevand** [comment]
@Chalarangelo i will do... 

Congrats for this amazing repo...  Very useful!

**Pull request merged**
