### PR TITLE
Improve factors

### PR DESCRIPTION
**Pull request by kriadmin**
## Description

Added some extra functionality to factors

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by kriadmin** [comment]
@Chalarangelo Even I can't think of any use-case but it might be useful at some places

**Comment by Chalarangelo** [comment]
Well, while it *might* be useful, this makes the snippet longer and harder to read. Unless we can find valid use-cases, I vote against merging these changes as they harm readability.

**Comment by kriadmin** [comment]
@Chalarangelo They add only like 3 lines of code which are easy to understand (easier than adapter functions).

**Comment by skatcat31** [comment]
while an improvement I'm of the opinion that `factors` is not a function we should have. It's long Math Golf which is a way of saying "won't use outside of academia" and teaches little about Javscript. We have a few snippets like this that need to be addressed.

Really when we think of snippets we should begin to start thinking "What can an advanced beginner learn from this snippet" of which this snippet in and of itself teaches nothing but math. Mathematicians often make AWFUL programmers.
___
adapter functions, while a little esoteric, teach the interface and first order language functionality of javascript and become extremely useful in chains of transformations since you can use them to build your own libraries for your project especially with the prevalence of Promises and SPA.

**Comment by kriadmin** [comment]
@skatcat31 I def agree with you that it teaches nothing new about Javascript. But it is definitely a useful snippet and is also easy to understand. We have many other math snippets and one more will not do any harm .

**Comment by Chalarangelo** [comment]
@skatcat31 We have a few too many math snippets and I feel like there are practical uses for them, especially provided how popular JS is nowadays. Yes, it's slow when doing super complex mathematical things, but I have found myself needing things like factorization a few times and I suspect many students that come here while in college might benefit from them. The point here is that while not teaching a lot about JS, they might be the selling point to a student trying to whip up a project for college and that might make them get into JS in the first place. That, and the fact that something like Matlab takes forever to learn, so I would suspect a few people might take a look and think they are cool.

We are getting a lot of more academic snippets nowadays, so we might want to invent a category for them to de-clutter math in the long run. 

@kriadmin As it currently stands, I am not sold on the extra functionality and I don't think we should really consider adding it in, provided that these snippets might end up archived/deleted in the long run. I'm closing the PR and I might reopen when/if we decide on what to do with academia-focused snippets.

**Comment by skatcat31** [comment]
I like the idea of moving Academic snippets out of Math maybe into an Academic category with a Math sub category.
___
As for the improvement aside from my feelings on the snippet:
This sort of improvement actively harms usability by having a hard to understand( albeit programatically faster ) API. I think a switch statement on a Boolean might have been a better idea with the cases being
```js
switch (primes) {
  case true:
    return array.filter(isPrime)
  case false:
    return array.filter(el => !isPrime(el))
  default:
    return array;
}
```

**Pull request closed without merging**
