### PR TITLE
[FEATURE] Add toSnakeCase

### PR DESCRIPTION
**Pull request by Chalarangelo**
Converts a string to snakecase.

## Description

**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#snakeCase

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by kriadmin** [comment]
`toSnakeCase('Teletubbies say Eh-oh')` returns `"_teletubbies_say__eh_oh"` on my google chrome console. Adding the following line in end will help 
`str.startsWith('-') ? str.slice(1,str.length) : str;`

**Comment by Chalarangelo** [comment]
@kriadmin Good edge case I missed, however that might be sub-optimal. Maybe there's a regex way to deal with that?

**Comment by kriadmin** [comment]
I already knew about this edge case from about a month ago. This can't be dealt with regex(according to me). Checking if it starts with '-' is the only solution(acc to me).

**Comment by Chalarangelo** [comment]
Alright, I'll not merge and wait for a couple more opinions until tomorrow. If there's no better (i.e. more elegant) way, this is a pretty decent fix nonetheless, so I'll update and merge later.

**Comment by iamsoorena** [comment]
@Chalarangelo I also see that the last test returns this:
`some_mixed_string__with_spaces_underscores_and_hyphens`
take a closer look before `with`
It added two underscores.

**Comment by Chalarangelo** [comment]
@iamsoorena Good catch, I'll see if I can figure out a way to update it tomorrow, then. Feel free to apply fixes if you figure it out before I do!

**Comment by elderhsouza** [comment]
@kriadmin @Chalarangelo 
I tried my hand on it, checking if the uppercase character is preceded by a character first.

**Comment by kriadmin** [comment]
@elderhsouza  Try this string.
`"The Spaced   Text""`

**Comment by kriadmin** [comment]
@elderhsouza Try this text "I  &nbsp; &nbsp; have &nbsp; Lot's of&nbsp;&nbsp; _Spaces"

**Comment by kriadmin** [comment]
What about `'ThisIsAURL'` ?

**Comment by Chalarangelo** [comment]
@kriadmin I see how you would want to handle this but I don't think that any library would handle it properly anyways.

**Comment by kriadmin** [comment]
@Chalarangelo Lodash returns `this_is_url`

**Comment by kriadmin** [comment]
@Chalarangelo See the second comment here https://github.com/lodash/lodash/issues/561 by jdalton

**Comment by Chalarangelo** [comment]
@kriadmin That would require a lot of code to handle just one (or a select few) cases. If it doesn't make the snippet very difficult to read, I'm not against it, however I am not sure I can implement this on my own. Suggestions are welcome, I'm marking this snippet `on hold`, although I believe the `toKebabCase` snippet was merged already by someone else and probably has similar issues. Can someone check and verify if it handles this specific edge case?

**Pull request merged**
