### PR TITLE
Create hexadecimal-to-RGB.md

### PR DESCRIPTION
**Pull request by Pl4gue**
Snippet for converting hexadecimal colorcodes to RGB colorcodes. Also makes use of ECMAScript, working proof here: [JSFiddle](https://jsfiddle.net/pl4gue/ozpLxqsk/)

### CODE REVIEW

**Comment by kingdavidmartins** [comment]
Hey @Pl4gue 👋 

I wanted to know if there was a reason you didn't go with  
```javascript
const hexToRgb = hex => hex.slice(1).match(/.{2}/g).map(x => parseInt(x, 16))
```
compared to what was submitted I believe this is more elegant and simpler

**Comment by kingdavidmartins** [comment]
@Pl4gue Also rather than return an array -> [#, #, #]. 
You could return your result in a rgb format -> rgb(#, #, #)

```javascript
const hexToRgb = hex => `rgb(${hex.slice(1).match(/.{2}/g).map(x => parseInt(x, 16)).join()})`
```

**Comment by skatcat31** [comment]
I feel like this could be a problem if people don't understand it's a hex color code string, not a hexidecimal number...

```js
const validHex = 0xFF // 255, but it's not a hex color code
```

**Comment by Pl4gue** [comment]
@skatcat31Thank you for the feedback, I'll rename it :+1:

**Comment by Pl4gue** [comment]
@kingdavidmartins Thank you for the feedback, I'll apply your suggestions :+1:

**Pull request merged**
