### PR TITLE
[FIX] lint-script.js

### PR DESCRIPTION
**Pull request by atomiks**
## Description
So after some debugging I found that using `.temp` made the linter not actually run. By removing it it works. I also cleaned the code style a bit... 

**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#(method) 

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [x] General / Things regarding the repository (like CI Integration)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## [Lodash Backlog](https://github.com/Chalarangelo/30-seconds-of-code/issues/100)

- [ ] I added the prefix [UPDATE: `method.md`] or [ADD: `method.md`]
- [ ] I have referenced the `method` to the lodash backlog.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by atomiks** [comment]
Ok so in order for the code to be properly normalized/formatted prettily, we DO need prettier as well.  `semistandard --fix` does help fix some issues but doesn't fully re-format it. 

So here I've added it to run after the `semistandard` command and used `.replace()` with some regex instead of `.slice()` to replace the file with the linted code since it's a bit easier to understand.

**Comment by atomiks** [comment]
No we need prettier because the linter formatting doesn't fix this one (and similar):

```js
const difference = (a, b) => { const s = new Set(b); return a.filter(x => !s.has(x)); };
```

It should break to new lines

**Comment by Chalarangelo** [comment]
No, it shouldn't. This is intentional, as we want snippets that can be displayed in one line to be displayed in one line (this is something we do manually so far).

**Comment by atomiks** [comment]
But that one shouldn't be displayed on a single line because it needs to be separated by a semicolon. It looks cluttered...

**Comment by Chalarangelo** [comment]
The whole styling thing is a flaming pile of garbage at this point, our guidelines aren't well-defined enough about things like this and we have no specific line length or anything to sort this issue. I would prefer if we jsut fixed the file extension problem in this PR and actually open an issue to discuss these guidelines, so we can then set up `prettier` with a set of well-defined rules that we have decided on as a community, wouldn't you agree?

**Comment by atomiks** [comment]
Yes that's a good idea. I'll ake a new PR with just the extension changes.

And we can also lint/prettier-ify the script files too

**Comment by Chalarangelo** [comment]
Yep, send a PR with the extension changes and let's open up a discussion for this to define the styling a little bit better then! Thank you! 👍

**Pull request closed without merging**
