### PR TITLE
toThousands

### PR DESCRIPTION
**Pull request by feiwen8772**
在一个数字上添加千分位分隔符

### CODE REVIEW

**Comment by feiwen8772** [comment]
Thank you, you are right!

**Comment by iamsoorena** [comment]
@feiwen8772 google translate says: 
this : 在一个数字上添加千分位分隔符
means : Add thousands separator character on a digital (to digits)
which is way more understandable.

**Comment by feiwen8772** [comment]
@iamsoorena Thank you! I close this PR，and Re-PR later。my English is so poor,I'm a Chinese 😩

**Comment by iamsoorena** [comment]
@feiwen8772 I will love to see you make this snippet work.

**Pull request closed without merging**
