### PR TITLE
Update `arrayToHtmlList` function

### PR DESCRIPTION
**Pull request by BrianDGLS**
## Description

The existing method has an unnecessary closure and string concatenation with `querySelector`.

To update I have removed the closure and used `getElementById` instead of `querySelector` combined with concatenating `'#'` to the supplied id.

Working example: [https://codepen.io/BrianDGLS/pen/MXyQoK](https://codepen.io/BrianDGLS/pen/MXyQoK)

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by ZAYEC77** [comment]
@BrianDGLS 
why did you close your MR?
your solution looks clearer than current as for me

**Comment by skatcat31** [comment]
@ZAYEC77 while it's more readable(and we should update this to the `getElementByID` method), it makes a global variable(huge no-no), and causes constant draws and is MUCH slower due to multiple modifications to the `innerHTML` attribute, which causes re-render and since it do done synchronously and without an animation frame will cause massive slowdown on lists of any significant size.

This can however be boiled down into a much more similar and simpler meshing of the two:

```js
const arrayToHtmlList = (arr, listID, format = ( item => `<li>${item}</li>`) ) =>
  document.getElementById(listID).innerHTML += arr.map(format).join('')
```

Of course there are still improvements that could be made here regarding performance probably... but this should only cause a single re-render.

**Comment by ZAYEC77** [comment]
@skatcat31 Thanks for the response.
What about solution like this:
```js
const arrayToHtmlList = (arr, listID) => (
    document.getElementById(listID).innerHTML = arr.reduce((acc, item) => acc + `<li>${item}</li>`, ''))
```

or more readable variant:

```js
const arrayToHtmlList = (arr, listID) => {
    const html = arr.reduce((acc, item) => acc + `<li>${item}</li>`, '')
    document.getElementById(listID).innerHTML = html
}
```

or `join` will be faster than concatenation at each iteration of `reduce`?

**Comment by skatcat31** [comment]
it's all flavor at this point. We should address it's form though. I'm going to migrate to a new issue about an update and whether we should change the footprint.

**Pull request closed without merging**
