### PR TITLE
[FEATURE] Elo rating system snippet

### PR DESCRIPTION
**Pull request by atomiks**
## Description

https://en.wikipedia.org/wiki/Elo_rating_system

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by skatcat31** [comment]
This is useful in multiplayer competitive leagues using ELO but ELO is now considered an out of date rating system for video games due to the extreme de-bouncing needed. While still used, it is instead preferred to use a more metric based approach to your games(truskill, skillz, other rating systems that take into account minute metrics to determine ratings).

ELO is still a valid rating system for games that use strategy for complexity. Such games are Chess, Go, or any perfect information symmetrical game. While a cool example, I'm not certain it has much use here since if it isn't one of these few games and it has minute differences in skill like 'headshot' or 'objective data' then it is an extremely inaccurate rating.

**Comment by atomiks** [comment]
Can you explain further about the debouncing? Is that to do with rating inflation or something?

Do you think it's accurate for a 1v1 game of Call of Duty where it's either win or loss? I've researched a bit and came across Glicko 2 and TrueSkill but their implementations are too complex for a snippet (I think).

**Comment by Chalarangelo** [comment]
I'm merging as this has practical uses, even if there are better ranking systems than this one. We can add more snippets like this anyways and someone might need this, so why not?

**Comment by skatcat31** [comment]
Debouncing and ELO rating are required to clamp gains based on differences in the ratings and how often you defeat opponents of the same rating as you, and opponents of a lower rating than you

**Pull request merged**
