### PR TITLE
Added getType function

### PR DESCRIPTION
**Pull request by macsmac**
Snippet to get native type of function (lowered-case constructor name)

### CODE REVIEW

**Comment by darrenscerri** [comment]
Finding it hard to find a use-case for this function. In what cases would this be useful?

**Comment by macsmac** [comment]
@darrenscerri

using this on my game server

```js
switch(getType(postres)) {
case "entity": /* ... */; break;
case "broadcast": /* ... */; break;
case "dataset": /* ... */;
}
```

**Comment by skatcat31** [comment]
I use an extremely similar function in a production environment as well since typeof is unpredictable in certain cases

**Comment by darrenscerri** [comment]
Interesting, that's a reasonable use-case.

**Comment by macsmac** [comment]
`instanceof` vs `getType`

```js
'use strict';

const getType = v => v === undefined ? "undefined" : v === null ? "null" : v.constructor.name.toLowerCase();

class A { constructor() { this.a = 1; } }
class B extends A { constructor() { super(); this.b = 2; } }

const b = new B();

console.log(b instanceof B); // true
console.log(b instanceof A); // also true

console.log(getType(b) === "b"); // true
console.log(getType(b) === "a"); // obviously false
```

**Pull request merged**
