### PR TITLE
Simplify intersectionBy

### PR DESCRIPTION
**Pull request by Siarhei-Zharnasek**
Simplify intersectionBy [ENHANCEMENT]

No need to use arrow function in b.map callback

## What does your PR belong to?
- [ ] Website
- [X] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have checked that the changes are working properly
- [X] I have checked that there isn't any PR doing the same
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by skatcat31** [comment]
It's odd how you just glance over the small stuff like that -.-;

**Comment by Siarhei-Zharnasek** [comment]
@skatcat31 sorry)

**Comment by skatcat31** [comment]
Not at all, a second set of eyes is always something I'm grateful for.

> Great leaders who do not head words of wisdom will often be replaced by those whose words they did not head

**Comment by skatcat31** [comment]
I am however going to await another approve to merge this in case they have any insight into why we didn't use a direct call there that I may have forgotten.

**Comment by Siarhei-Zharnasek** [comment]
🤞

**Pull request merged**
