### PR TITLE
[ADD: zipWith.md]

### PR DESCRIPTION
**Pull request by kriadmin**
## Description

**Resolves** #100 

**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#zipwith

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## [Lodash Backlog](https://github.com/Chalarangelo/30-seconds-of-code/issues/100)

- [x] I added the prefix [UPDATE: `method.md`] or [ADD: `method.md`]
- [x] I have referenced the `method` to the lodash backlog.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by kriadmin** [comment]
@skatcat31 Updated

**Comment by skatcat31** [comment]
Hmm something I just noticed this defaults to zip if there is no function in the last argument. I'm not certain if this should be an intended behavior pattern to avoid two snippets that do the same thing, or if we should replace zip with this snippet. @Chalarangelo @kingdavidmartins @fejes713 any input on that pattern?

**Comment by skatcat31** [comment]
otherwise great submission!

**Comment by Chalarangelo** [comment]
My opinion is to replace `zip` with this implementation, defaulting to the original `zip` behavior without a function in the arguments, like we have done with other snippets. Seems easy enough to understand in my opinion.

**Comment by kingdavidmartins** [comment]
@skatcat31 Although I agree with you with the following

> Hmm something I just noticed this defaults to zip if there is no function in the last argument. I'm not certain if this should be an intended behavior pattern to avoid two snippets that do the same thing.

One thing I think we also need to take into account is how quickly a beginner can really pick & understand what the code is doing. Although `zipWith` can replicate `zip` if 2nd arg is omitted. I think if we completely replace `zip` with said code we will be adding more code which could reduce the readability/simplicity of them understanding the code. 

I also realized that what we believed as "simple" may really not be the case when a few people I met at a meet up who started learning JS couldn't really grasp some of the snippets I thought were relatively easy. I believe having something our users can build off to learn from so they can see how things connect and etc is useful. Rather than just removing `zip` entirely.  

The way I see it `zipWith` is a more advance version of `zip` such as users can have more control of how things are zipped. 

**Note:** I was think having a little pointer in the description can go a long way for snippets like these pointing users who feel the current snippet is too hard to a easier simpler version.

Like `if this snippets seems a bit more than you can handle checkout out our zip snippet`

@Chalarangelo Thoughts?

**Comment by Chalarangelo** [comment]
Iterlinking snippets will lead to a situation where we have to maintain links atop of the snippet list, which leads to all sorts of problems when archiving, renaming, removing etc. Marking snippets as `advanced` was a decent first step, maybe we want to add a difficulty rating via a system, so it's easy to understand the relative level of difficulty for a JS user. That being said, what might be hard for me to grasp might be super easy for someone else and vice versa, so in general this is very subjective and won't work out too well.

Keeping both snippets, in this case, makes more sense probably as the `zipWith` one is complex enough to require some extra time to read through. Sticking an `advanced` tag can certainly help, plus `zip` is right above or below it anyways, so discoverability is a non-issue here.

**Comment by kingdavidmartins** [comment]
>  plus zip is right above or below it anyways, so discoverability is a non-issue here.

@Chalarangelo haha 😆 Of course I totally forgot. Makes Sense!

I also think an advance tag can go some ways. 

Maybe anythings with over a certain amount of lines maybe 5, and two/or more of the following closures, reduce, `...` operator, or.....

I don't just brainstorming here. Any other ideas? 

Thoughts @skatcat31 ?

**Comment by skatcat31** [comment]
I think they idea of keeping this as is and keeping zip might be a good idea if we mark this advanced since it shows people something most of our other snippets don't, the special function type

**Comment by kriadmin** [comment]
@skatcat31 @Chalarangelo @kingdavidmartins I don't think this snippet is too advanced and can also be called very easy to understand in comparision to the lodash code. And I checked the behavior of `_.zipWith` and it is the same so I think we can keep them both.

**Pull request merged**
