### PR TITLE
[FEATURE] btoa and atob

### PR DESCRIPTION
**Pull request by Chalarangelo**
## Description

Adds two snippets for Node, `atob` and `btoa`, similar to the browser methods [`atob`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/atob) and [`btoa`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa).

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by kingdavidmartins** [comment]
Doubt beginners will look up 
- atob()
- btoa()

Seems highly improbable

However believe there's value if both have simple names so a beginner / users can quickly search up base64 Encode / Decode & get it

**Comment by Chalarangelo** [comment]
Actually, beginners do look for those when using node, as they exist in browsers and not in Node. I have found myself multiple times in the past looking for a solution to a problem, only to find out a solution that uses `btoa`. Fast forward ten minutes later adn I realize that Node doesn't have this built-in. Main reason I named them like this is that people who know where to use them, know what they are called and they usually have seen them in their browser form.

**Comment by skatcat31** [comment]
I agree with @Chalarangelo, @kingdavidmartins I have on several occasions needed to explain that `btoa` and `atob` don't exist in Node -.-

It's always surprised me they find those so easily

**Comment by kingdavidmartins** [comment]
@Chalarangelo  & @skatcat31 Makes sense!

**Pull request merged**
