### PR TITLE
[FIX] kebabCase styling + remove global variable + handle empty string

### PR DESCRIPTION
**Pull request by atomiks**
## Description

As title says

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Chalarangelo** [comment]
I like the changes. My only question is what was the global variable you mentioned, what am I missing exactly?

**Comment by atomiks** [comment]
`let regex = rx = `

The `rx` becomes a global variable once the function is run.

**Comment by Chalarangelo** [comment]
Ah, I see!

**Comment by Chalarangelo** [comment]
@atomiks Nevermind, I actually just did that, as it was really quick and simple. Thanks for the great contribution once again!

**Pull request merged**
