### PR TITLE
Add toHash snippet

### PR DESCRIPTION
**Pull request by skatcat31**
## Description

A thing I've found myself using a LOT recently to create single pass closures so that I can grab a referenced object based on an identifier in another array. Useful for unfolding loops so you only have to loop over a data set once before referencing them later

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project. -- I may have to many spaces in my code formatting... I keep forgetting how semi standard sets that...
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Chalarangelo** [comment]
I like the idea, but description could be a bit more descriptive and I think we are missing an explanation. Also, isn't the name a bit confusing or am I misunderstanding the functionality? 

*Don't get me wrong, we are gonna merge this, we just need to polish it up a tiny bit*

**Comment by skatcat31** [comment]
The name is to show that an iterator passed in returns a hash(keyed data store)

I could probably clean up the description and add an explination

**Comment by skatcat31** [comment]
Updated with a description, and making it Array Like

**Comment by skatcat31** [comment]
sadly what brought this idea about is how often I'm joining multiple data-sources together now and how often I only want one loop over each instead of `O(nm)` loops

**Pull request merged**
