### PR TITLE
Added snippet to remove duplicate elements from an array

### PR DESCRIPTION
**Pull request by arjunmahishi**

### CODE REVIEW

**Comment by meetzaveri** [comment]
Hey @arjunmahishi I think this snippet has been included with much smaller code - https://github.com/Chalarangelo/30-seconds-of-code#unique-values-of-array . Anyways thanks for your effort!

**Comment by Chalarangelo** [comment]
@arjunmahishi Thanks for contributing! However, I think this is a duplicate of an existing snippet as @meetzaveri mentioned.

**Comment by arjunmahishi** [comment]
Ohh. Damn! didn't see that.

**Comment by Chalarangelo** [comment]
No problem, things have been changing around a lot, so don't worry about it. 😉

**Comment by arjunmahishi** [comment]
Is there a TODO list or something with a list of unimplemented ideas?

**Comment by Chalarangelo** [comment]
@arjunmahishi Check #100, lots of things that need implementation. 😉

**Pull request closed without merging**
