### PR TITLE
Get rid of arguments for bind

### PR DESCRIPTION
**Pull request by Siarhei-Zharnasek**
Get rid of arguments for bind [ENHANCEMENT]

Soon arguments will be deprecated

## Description
Use native method reduce instead of array looping.

## What does your PR belong to?
- [ ] Website
- [X] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have checked that the changes are working properly
- [X] I have checked that there isn't any PR doing the same
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by skatcat31** [comment]
So arguments is kind of a weird thing in that arguments is a collections of arguments but it requires us to use a long hand function instead of an arrow function. With the arrow function however we gain brevity and uniformity without introducing a magic variable. As long as it works the same this is a great improvement because it gets rid of the magic arguments variable(something a lot of people are pushing for, no more magic)

**Comment by Chalarangelo** [comment]
@skatcat31 But the question is *does it work as expected?*

**Comment by Siarhei-Zharnasek** [comment]
Let's remove all magic from javascript!

**Comment by skatcat31** [comment]
@Chalarangelo it says hi to fred just fine

**Pull request merged**
