### PR TITLE
[FEATURE] Add mapAsync snippet

### PR DESCRIPTION
**Pull request by Birkenstab**
## Description
Maps the values of an array using the async function provided. Returns a promise that resolves with an array that contains all mapped values

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [ ] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by skatcat31** [comment]
I'm not such a fan since it's obfuscating already hard to understand concepts and is merely a wrapper

```js
var a = [1,2,3]
var b = a.map(i => setTimeout(() => Promise.resolve(i*2),0))
Promise.all(b)
```

behaves the same, and it's obvious what you're doing there, making debugging MUCH simpler than

```js
mapAsync(a, fn)
```

which begs the question of "Which order is it async?" Is the Array async and the function executing after it all resolves, or is the mapping Async?

**Comment by Chalarangelo** [comment]
@skatcat31 I am not entirely certain about the implementation specifics and the way this behaves, but the main question that begs asking for me is if we really need this snippet and if it has valid and common enough use-cases.

**Comment by skatcat31** [comment]
Valid common use case is less typing in a common factor, however it is confusing no matter which way you implement it because mapAsync does not describe how it's deciding to map and there can be no standardized way to describe it with a short name that would actually make it more useful.

```js
a = [1,2,3]
mapAsync(a, fn)
// vs
Promise.all(a.map(fn))       // implimented the way it is here as map all then resolve
// vs
Promise.all(a).then(b => b.map(fn))       // another mapAsync( resolve all, then map )
// vs
new Promise((resolve) => setTimeout(() => resolve(a),0)).then(b => b.map(fn))        // another mapAsync( push, then map )
```

But as you can see all of these could be called mapAsync which is the problem. which GREATLY limits the usefulness of this snippet and whether we'd need it( confusion over functionality is NEVER good )

**Comment by Chalarangelo** [comment]
I'm pretty sure this would confuse users as it does confuse me even after I took a long hard look at it. Does it qualify as archive material or should we just close the PR altogether, @skatcat31 ?

**Comment by skatcat31** [comment]
We should close altogether due to the ambiguous nature of most functions called mapAsync and how little it ends of up saving in terms of development since if you know you're going to map to an array of Promises, you also know you're going to us a Promise.all, and at that point non promise transformations are no longer able to be chained and you'd return to a different context where the Promise.all would be called from then and continued on.

**Comment by skatcat31** [comment]
To be fair, this use pattern comes up A LOT, but it is not something that can easily be named or reasoned, so closed it is

**Comment by Birkenstab** [comment]
Ok, no problem

**Pull request closed without merging**
