### PR TITLE
Snippet to implement clamping

### PR DESCRIPTION
**Pull request by arjunmahishi**
## Description

Added new snippet

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by skatcat31** [comment]
I think people may be confused what you're doing with the array at first(using the assignment operator inside an assignment to chain). Otherwise great snippet

**Comment by arjunmahishi** [comment]
Thank you! :smile:

**Comment by kingdavidmartins** [comment]
Hey @arjunmahishi 👋 

Also if the function is similar to lodash -> https://lodash.com/docs/4.17.4#clamp
Referencing it to the lodash log #100 will make updating the list much easier. Thanks loads 😄

**Comment by arjunmahishi** [comment]
Sure!! will keep that in mind next time :)

**Pull request merged**
