### PR TITLE
[FEATURE] add infixToPostfix and postfixToInfix

### PR DESCRIPTION
**Pull request by kriadmin**
## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by kingdavidmartins** [comment]
Also I believe this is data structure specific & as such I believe adding other categories representing different operations/manipulation of other data structures other than arrays can also be beneficial to the project.

Example:
linkedList:
DoubleLinkedList:
DFS
BFS
Trees
Tries
Etc

Thought's @Chalarangelo

**Comment by kriadmin** [comment]
@kingdavidmartins I didn't add proper description as I am waiting for suggestions to imporve the second snippet(postFix to Infix)

**Comment by skatcat31** [comment]
Do we want to keep allowing more RPN stuff? I know we have the solveRPN snippet, but are we certain we want to go deeper with things like translators? They are large, but interesting. I'm just not certain they fall under '30 seconds to understand'... especially with how esoteric RPN is these days

**Comment by kingdavidmartins** [comment]
Honestly @skatcat31 I agree

> especially with how esoteric RPN is these days

Couldn't have said it better myself. Def takes more than 30 seconds to grasp and as such out of scope with the current project.

Personally I believe we should vote to decide if we want to merge/add the following snippets into the project

I vote it shouldn't for the described reasons above 👎

**Comment by kriadmin** [comment]
Even I think this snippets are too big and belong in 30-hours-of-code. I support @kingdavidmartins 's decision to remove these snippets but I think we should first ask @Chalarangelo .
If he agrees I will close the PR

**Comment by Chalarangelo** [comment]
Ah, hadn't seen the discussion when I reviewed. Yeah, I think these are pretty hard to grasp in 30 seconds or so. Based on the fact that we all agree that they are too long, I'm closing the PR.

**Pull request closed without merging**
