### PR TITLE
ADD: toKebabCase.md and repeatString.md

### PR DESCRIPTION
**Pull request by kriadmin**
## Description

**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#repeat
**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#kebabCase 

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking improvement of a snippet)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## [Lodash Backlog](https://github.com/Chalarangelo/30-seconds-of-code/issues/100)

- [x] I added the prefix [UPDATE: `method.md`] or [ADD: `method.md`]
- [x] I have referenced the `method` to the lodash backlog.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by kriadmin** [comment]
Why did you change the default num to 2 in repeatString.md?

**Comment by Pl4gue** [comment]
@kriadmin Because the purpose of repeatString is to repeat the given string. You don't have any value of using this function with default parameter num=1 as you could just use the string instead in this case.

**Comment by kriadmin** [comment]
@Pl4gue But in lodash the default value is 1 so I thought..

**Comment by Pl4gue** [comment]
@kriadmin We are neither a imitation of Lodash, nor a substitution. We implement the snippets in a way they seem most sensible to *us*, not to the lodash guys :smile:

**Pull request merged**
