### PR TITLE
[FIX] Hyper speed-boost lint-script to lint examples + use prettier formatting

### PR DESCRIPTION
**Pull request by atomiks**
## Description

Makes it like 60x faster by running semistandard on the entire folder. Lints and prettifies both the function definition and example blocks

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [x] General / Things regarding the repository (like CI Integration)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by skatcat31** [comment]
I'm curious why we're reading it one synchronously instead of using chaining?

**Comment by atomiks** [comment]
What do you mean? From what I've read, sync read/write methods are faster than async ones. The total linting takes around 1s-3s on my laptop.

**Comment by kingdavidmartins** [comment]
I agree with @atomiks 

> sync read/write methods are faster than async ones.

Especially for the purpose of this project. Since we will be running it on our machines and not on a web server of sorts. I believe It makes sense to go this route.

[SO](https://stackoverflow.com/questions/13822085/fs-readfilesync-seems-faster-than-fs-readfile-is-it-ok-to-use-for-a-web-app-in)
[Medium](https://medium.com/@adamhooper/node-synchronous-code-runs-faster-than-asynchronous-code-b0553d5cf54e)

**Comment by skatcat31** [comment]
I misread a section of the commit diff. When looking at the full file it becomes a little more clear what's happening( I use a color changing app that had a hiccup apparently, making the removed code look like it was still present ). It looked to me like we were manually linting each file and then sending ti to prettify synchronously instead of async, or as a folder. Now that I see it's over the whole folder, yeah no this is fine XD

Perfect storm:
 - Web colorizer
 - Automatic contrast negotiation on graphics card driver when not in game
 - Blue Light reducer

Surprised it hasn't been an issue until now, but this is the largest stream of commits I've seen in awhile in one MR in this project.

**Pull request merged**
