### PR TITLE
Update palindrome

### PR DESCRIPTION
**Pull request by iamsoorena**
use spread operator and change regex implementation to more conventional `/\s+/g` to match white-space.

### CODE REVIEW

**Comment by iamsoorena** [comment]
I'll do it asap

**Comment by wojtekmaj** [comment]
I'm not so sure about being "definitely" faster.

https://jsperf.com/30sec-palindrome

On Chrome, I get consistently lower performance. On Edge, spread operator is 4 (!) times slower.

obraz

Interestingly, spread operator *is* faster on Firefox 57.

**Comment by iamsoorena** [comment]
@Chalarangelo what is your opinion about @wojtekmaj comment? I think he is right even if spread operators seem more like native code.

**Comment by Chalarangelo** [comment]
@wojtekmaj Thanks for pointing that out, I am primarily a Firefox user, so tests were giving better results with spread operator for me.

**Comment by atomiks** [comment]
I prefer using the nifty `timeTaken` function:

```js
// split
timeTaken(() => palindrome1('racecar'.repeat(1000000)))
// Chrome: timeTaken: 347.054931640625ms
// Firefox: timeTaken: 288.46ms

// ...spread
timeTaken(() => palindrome2('racecar'.repeat(1000000)))
// Chrome: timeTaken: 762.1259765625ms
// Firefox: timeTaken: 696.11ms
```

So using `split` is over 2x faster in both.

**Comment by Chalarangelo** [comment]
@atomiks the spread operator is pretty slow then, although jsPerf indicated otherwise in most tests I have run. Let's stick with `split()` then as it is faster.

**Pull request closed without merging**
